[package]
name = "wasm_map_lookup"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = {version="1.0"}
clap = {version="4.5", features = ["derive"]}
anyhow = {version="1.0"}